### ISSUE TITLE
Merge not working 

### ISSUE THREAD

**Issue by AndrewChubbs** [Garbaz/anki-merge-duplicates#3]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-09-29 14:25:09
Add-ons possibly involved: ⁨Merge duplicate notes⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/AndrewHerson 1/Library/Application Support/Anki2/addons21/55394168/__init__.py", line 30, in merge_duplicates
    mode = config.get("merge_mode", "longer")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Garbaz** [comment]
Does this happen every time? Or was this a one time occurrence?

Because I don't quite see how this can happen without Anki somehow messing up ._. What this error is saying in essence, is that when the addon asked Anki for it's configuration at startup, Anki gave nothing back. And I am not really aware of any nicer way to ask Anki for the configuration ^^

What you could check is that if you go to `Tools->Addons->merge_duplicates->Config` that it contains the following text:
```
{
    "merge_mode": "longer"
}
```

**In any case, I will add some code to catch this possibly 👍 Thank you for reporting!**
